extensions: {}
cabal-file: project.cabal
extra-packages: ''
version: 1
environment: ghc-7.4.2-stable-13.06
module-template: ! 'module MODULE_NAME where

'
ghc-args: []
modules:
  Main(test/Spec.hs):
    filename: test/Spec.hs
  Control.Foldl:
    filename: src/Control/Foldl.hs
